### ISSUE TITLE
Image URL's

### ISSUE THREAD

**Issue by betty02** [DREW1990/JAMF-Inventory-Collector-GUI#2]
I know this isn't an image as such but I tried to change the '''SCRAMBLEDTEXT''' to an image to use for myself, I presume I can't just copy a path? How would I go about changing the image?

Thanks

**Comment by betty02** [comment]
Problem I am having is I am using an Image to Base64 convertor, and uploading my image, converting and it gives me the code, enter the code and then run the script again and get this output - 

`Traceback (most recent call last):
  File "/Users/sbe47/Downloads/JAMF-Inventory-Collector-GUI-master/inventory_collector.py", line 233, in <module>
    app = InventoryCollector(root)
  File "/Users/sbe47/Downloads/JAMF-Inventory-Collector-GUI-master/inventory_collector.py", line 54, in __init__
    self.logo = tk.PhotoImage(data=inventory_collector_logo)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk/Tkinter.py", line 3366, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk/Tkinter.py", line 3320, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: couldn't recognize image data`

But if I get the code and decode it online it shows my image and if I enter your Base64 code back in it works?
